global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "prometheus_rules.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9100"]  
   
  - job_name: "services"
    metrics_path: /metrics
    static_configs: 
      - targets: 
          - 'init:8080'
          - 'layer1_1:8080'
          - 'layer1_2:8080'
          - 'layer1_3:8080'
          - 'layer1_4:8080'
          - 'layer1_5:8080'
          - 'layer2:8080'
          - 'layer3_1:8080'
          - 'layer3_2:8080'
          - 'layer3_3:8080'
          - 'layer3_4:8080'
          - 'layer3_5:8080'
          - 'core:8080'
